### ISSUE TITLE
bug [lesechos.fr]

### ISSUE THREAD

**Issue by oliwer** [bpc-clone/bpc_firefox_support#297]
Since today (16 December) lesechos.fr (and all the sites of the group) are broken again (paywall).

Link of paywalled article: https://www.lesechos.fr/industrie-services/tourisme-transport/le-rer-de-nouvelle-generation-calvaire-de-lile-de-france-voit-le-bout-du-tunnel-2138087

Actions I tried: clear cookies, but it did not work

Browser (main version): Firefox 132

BPC-extension version (number): 3.9.6.0

**Comment by bpc-clone** [comment]
Site fixed in latest master (or next release).\
PS until next release you can use the fr-userscript (& disable site in add-on).

Update: signing of latest releases is still delayed (holiday season) ...\
For now you can also use Chrome extension.

**Comment by oliwer** [comment]
Thanks! I used the userscript-fr and it worked fine the past few days, but this morning it seems to be broken again :cry:  I wonder if Les Echos are monitoring your changes.

Also broken with the extension v3.9.6.4

**Comment by oliwer** [comment]
Oh right, my bad.

**Comment by zulufoxtrot** [comment]
Tried latest master today. Looks like it's still broken or the site changed again.
